version: "3"
services:
       dyte:
           container_name: dyte
           image: dyte
           restart: always
           build: .
           ports:
             - "7500:7500"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'